[build]
  publish = "public"
  # This line MUST correctly point to your functions folder.
  functions = "netlify/functions"

[functions]
  included_files = ["data/**"]
  node_bundler = "esbuild"
  node_version = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200